name: IPv4 IPv6 App CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  validation-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify HTML File
        run: test -f index.html

      - name: Verify CSS File
        run: test -f style.css

      - name: Verify JavaScript File
        run: test -f script.js

      - name: Pipeline Success
        run: echo "All validation tests passed."
